# Generated by Django 4.2.6 on 2023-11-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdata',
            name='rating_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='total_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
