# Generated by Django 4.2.6 on 2023-11-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_trainingdata_create_trainingdata_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingData',
        ),
    ]
